collections:
  - name: https://github.com/ansible-content-lab/azure_ansible_deployment.git
    type: git
  - name: https://github.com/ansible-collections/azure.git
    type: git
    version: ">=2.3.0"