name: 'Destroy Azure'
on:
  workflow_dispatch:

jobs:
  Ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.LOCAL_SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          cp local/id_rsa.pub ~/.ssh/id_rsa.pub
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/id_rsa
          

      - name: Install Ansible Collections and Python Dependencies 
        run: |
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          if [ -f collections/requirements.yml ]; then ansible-galaxy collection install -r collections/requirements.yml; fi
          ansible-galaxy collection install azure.azcollection --force
          pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

      - name: Destroy Command
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          ansible-playbook lab.azure_deployment.destroy_infrastructure --extra-vars "aap_red_hat_username=${{ secrets.AAP_RH_USERNAME }} aap_red_hat_password=${{ secrets.AAP_RH_PASSWORD }}" \
            -e "ansible_python_interpreter=`which python3`" \
            -e deployment_id=chrrpbol